#↓に公式の本の数　ようするにbooksの下の数
#↓だと3
Number: 3
#下に本の名前、内容を保存
books:
  #本のタイトル(表示名でもある)一覧
  names:
    - "rule"
    - "test1"
    - "test2"
  #以下からほんのタイトル(↑と同じ)とほんの内容
  #行ごとにページ変わる
  #ダブルクォーテーションでくくると改行とかカラーコードが使えます・。・
  rule:
    - 内容1
    - 内容2
  test1:
    - 内容テストぉ\n改行も試してみる
  test2:
    - 内容です2内容です内容です内容です内容です内容です内容です内容です内容です内容です内容です