#↓に公式のほんの数
Number: 3
#下に本の名前、内容を保存
books:
  names:
    - rule
    - test1
    - test2
  rule:
    - 内容1
    - 内容2
  test1: 内容です1内容です内容です内容です内容です内容です内容です内容です内容です内容です内容です
  test2: 内容です2内容です内容です内容です内容です内容です内容です内容です内容です内容です内容です